### ISSUE TITLE
Undefined `clusters[minIndex]` heisenbug 

### ISSUE THREAD

**Issue by ajtadeo** [ajtadeo/Spotipi#2]
When running `kmeans` on a new albumID, the following error message appears randomly on the following code:
```
TypeError: Cannot read properties of undefined (reading 'push')
    at kmeans (/Users/ajtadeo/GitHub/Spotipi/kmeans.js:128:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fetchColors (/Users/ajtadeo/GitHub/Spotipi/app.js:70:22)
    at async Request._callback (/Users/ajtadeo/GitHub/Spotipi/app.js:101:30)
```

```js
// kmeans.js

async function kmeans(albumURL) {
  // ...
  while (true) {
    // for each point, determine euclidean distance to each centroid and add it to the closest centroid cluster
    iters++
    var clusters = [[], [], [], [], []]
    for (var i = 0; i < pixelDataLAB.length; i++) {
      var distances = []
      for (var j = 0; j < 5; j++) {
        distances.push(deltaE(pixelDataLAB[i], centroids[j]))
      }
      var minIndex = distances.indexOf(Math.min(...distances))
      clusters[minIndex].push(pixelDataLAB[i]) // ERROR HERE
    }

// ...
```

This results in an infinite loop running `kmeans` and a memory leak:
```
(node:3756) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Connection]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

This might be a result of the postgres db code since that was the latest change.

**Comment by ajtadeo** [comment]
its not an infinite loop because we run `fetchColors` every 5 seconds. however, if one run of `kmeans` fails and the album changes on spotify, the run for the new song may or may not succeed. something must be wrong with awaiting `kmeans` in `fetchColors`?

**Comment by ajtadeo** [comment]
looks like some albums consistently trigger this error, such as https://i.scdn.co/image/ab67616d0000b273c9281db15ef83b5f2ef5a9b7. must be a bug within the kmeans algo!

**Comment by ajtadeo** [comment]
when `centroids` has pixel values that are the exact same, NaN values appear on the next iteration of the while loop. 

iteration 1:
```
[
  [ 90.51369650512582, 1.1782532809680446, 0.9552933342825476 ],
  [ 90.51369650512582, 1.1782532809680446, 0.9552933342825476 ],
  [ 90.51369650512582, 1.1782532809680446, 0.9552933342825476 ],
  [ 90.51369650512582, 1.1782532809680446, 0.9552933342825476 ],
  [ 89.05161230606822, 0.8317039118753144, 1.9364128236512235 ]
]
```
iteration 2:
```
[
  [ 91.96934895819652, 0.8926611917654488, 0.6689289548660149 ],
  [ NaN, NaN, NaN ],
  [ NaN, NaN, NaN ],
  [ NaN, NaN, NaN ],
  [ 68.52780163325929, -2.75807448807655, -17.174939202011178 ]
]
```

**Comment by ajtadeo** [comment]
sometimes with album art that thats all one color, the randomly selected centroids and clustering that follows results in #clusters < k. taking the mean of 0 LAB values in a cluster results in [NaN, NaN, NaN] being added as a new centroid.

**Comment by ajtadeo** [comment]
possible solutions listed in this article: https://towardsdatascience.com/extracting-colours-from-an-image-using-k-means-clustering-9616348712be

> Oh, one more thing!
>
> 
> There is one issue with this algorithm, and it’s that sometimes the clusters become empty. There isn’t much of a consensus on what to do when this happens, but some possible approaches are to:
>
> * Remove the cluster (a bit silly)
> * Assign a random data point to the cluster
> * Assign the closest data point to the cluster
> * Restart the algorithm and hope it doesn’t happen again
>
> Although the last option seems like a bit of a bodge, the algorithm (with the random initialisation) is non-deterministic and so simply restarting does work quite well. After all, this method is pretty much a heuristic and heuristics by definition are ‘a bit of a bodge’ … at least compared to a solid algorithm.

**Comment by ajtadeo** [comment]
fixed with https://github.com/ajtadeo/Spotipi/commit/3e53d1612a1f335c0f466adcd7311aead92ae2ab
